SESSION_NAME=1BQANOTEuMTA4LjU2LjEzMAG7MnmCKneRZL4/2BMFiLv8rl1upUtSirwVTKSBfeb/sq2wRejDmb2c97vgorRDgMYa5psYd2JiAVYdmja6Fo4tqtyxXqBzkBqTVt20Troq26a446bgsjEJz+BGSQAoYTsxbN2shOouVmYmKH16v1nvGE9tVdQo9N33p+hFH+ajEbMQSEXiNSxHJAuX6n+BPUnTkVcFAbxWk8Skaesj9TFdCiF2R7buuKsLUBalaRRvasm6fFmqGL9KtV/ZjvGXeD0r0xm0dn1g7AUQgLCMQ4msVwOP45R9V5MmcTz+riEtb9zG7f3tPXXt1Er0FSZ1eWhMKiIFnymMQJcmReIycvAwUw== # If you don't deploy with docker, keep it as is and if you do so it should be a session string generated by "python str.py"
BOT_TOKEN=2030043966:AAGxLhXyFIqv4JLjIzYJcJ4X_Q1-bRstur0
BOT_NAME=Dark Music Player
API_ID=3047095
API_HASH=994ffa4835a9c6fb1d697bdf283addbc
SUDO_USERS=1277798523 # List of user IDs separated by space
DURATION_LIMIT=150 # in minutes (default: 7)
ARQ_API_KEY=ITVOSR-IFISXP-KAIAFU-TQHYHY-ARQ
UPDATES_CHANNEL=ehi_podda
BG_IMAGE=
